import React from "react";
import { show } from "./format";

/**
 * End-of-report rule and disclaimer box, in the bureau's closing arrangement.
 * The wording is our own — no third-party disclaimer text is reproduced.
 */
export default function ReportFooter({ header, consumerName }) {
  return (
    <footer>
      <div className="cr-end">
        <span className="cr-end-text">
          End of report{consumerName ? ` on ${consumerName}` : ""}
        </span>
      </div>

      <div className="cr-disclaimer-box">
        <div className="cr-label">Disclaimer</div>
        <p className="cr-disclaimer">
          This report is generated by Surjit Finance from credit bureau data retrieved
          through our authorised data provider at the time of the enquiry. The
          information reflects what the bureau returned for this applicant and may be
          incomplete where a credit institution has not reported a field. Values shown
          as &quot;-&quot; or &quot;Not Available&quot; were not present in the bureau
          response. This document is prepared for internal credit assessment only and
          should be read alongside the other checks in the applicant file.
        </p>
      </div>

      <div className="cr-footer-meta">
        <span>Reference: {show(header.referenceNumber)}</span>
        <span>Generated: {show(header.reportDate)} {show(header.reportTime)}</span>
      </div>
    </footer>
  );
}
