import React from "react";
import { show } from "./format";

/** End-of-report block: original disclaimer, no third-party wording copied. */
export default function ReportFooter({ header, consumerName }) {
  return (
    <footer className="cr-footer">
      <div className="cr-end">End of report{consumerName ? ` for ${consumerName}` : ""}</div>
      <h3 className="cr-h3">Disclaimer</h3>
      <p className="cr-disclaimer">
        This report is generated by Surjit Finance from credit bureau data retrieved
        through our authorised data provider at the time of the enquiry. The
        information reflects what the bureau returned for this applicant and may be
        incomplete where a credit institution has not reported a field. Values shown
        as &quot;-&quot; or &quot;Not Available&quot; were not present in the bureau
        response. This document is prepared for internal credit assessment only and
        should be read alongside the other checks in the applicant file.
      </p>
      <div className="cr-footer-meta">
        <span>Reference: {show(header.referenceNumber)}</span>
        <span>Generated: {show(header.reportDate)} {show(header.reportTime)}</span>
      </div>
    </footer>
  );
}
