import React from "react";
import { show } from "./format";

/**
 * Closing block: the end-of-report rule, the disclaimer box and the footer
 * line, in the sheet's arrangement.
 *
 * The wording and the attribution are OURS — no third-party disclaimer text,
 * copyright line or corporate identifier is reproduced.
 */
export default function ReportFooter({ header, consumerName }) {
  return (
    <footer>
      <div className="cr-end">
        <span className="cr-end-text">
          End of report{consumerName ? ` on ${consumerName}` : ""}
        </span>
      </div>

      <div className="cr-disclaimer-box">
        <div className="cr-disclaimer-head">Disclaimer</div>
        <p className="cr-disclaimer">
          This report is generated by Surjit Finance from credit bureau data retrieved
          through our authorised data provider at the time of the enquiry. The
          information reflects what the bureau returned for this applicant and may be
          incomplete where a credit institution has not reported a field. Values shown
          as &quot;-&quot; or &quot;Not Available&quot; were not present in the bureau
          response. This document is prepared for internal credit assessment only and
          should be read alongside the other checks in the applicant file.
        </p>
      </div>

      <div className="cr-footer-meta">
        <div>
          Reference: {show(header.referenceNumber)} &nbsp;·&nbsp; Application:{" "}
          {show(header.applicationNo)} &nbsp;·&nbsp; Generated:{" "}
          {show(header.reportDate)} {show(header.reportTime)}
        </div>
        <div><strong>Surjit Finance</strong> — internal credit information report</div>
      </div>
    </footer>
  );
}
