import mongoose from "mongoose";

/**
 * Application — the SINGLE source of truth for a loan application.
 *
 * As of the Core Backend Redesign (Phase 2) an Application is created in one
 * write by the Admin Backend (POST /api/applications). There is no longer any
 * Applicant / CoApplicant / VehicleDetails source collection and no merge step.
 *
 * Backward compatibility: the field names read by the existing admin workflow
 * (applicant, coApplicant, vehicleDetails, dealer, dealerDetails, status,
 * workflowStage, history, timestamps) are preserved EXACTLY. New sections
 * (documents, branch, audit) are additive and never rename existing fields.
 *
 * applicant / coApplicant / vehicleDetails are stored as flexible objects
 * (Mixed) so the full payload sent by the dealer app is preserved without loss,
 * matching how the merged document behaved previously.
 */
const applicationSchema = new mongoose.Schema(
  {
    // ── Correlation id (generated by the dealer app) ─────────────────────────
    formId: String,

    // ── Embedded parties (flexible objects, full payload preserved) ──────────
    applicant: Object,      // { name, mobileNumber, email, aadharNo, panNo, address, photo, ... }
    coApplicant: Object,    // { name, mobile, email, relation, ... }
    vehicleDetails: Object, // { brandName, modelName, priceOfVehicle, financeRequired, tenure, ... }

    // ── Documents (image / file URLs, denormalized for convenience) ──────────
    // Populated from the applicant / coApplicant / vehicle image fields at
    // creation time. The original fields remain inside the objects above.
    documents: {
      applicant: {
        photo: String,
        aadharFront: String,
        aadharBack: String,
        panImage: String,
      },
      coApplicant: {
        photo: String,
        aadharFront: String,
        aadharBack: String,
        panImage: String,
        form60: String,
      },
      vehicle: {
        vehiclePhoto: String,
        vehicleImage: String,
      },
    },

    // ── Dealer (owner) — reference + denormalized snapshot ───────────────────
    dealer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    dealerDetails: {
      _id: mongoose.Schema.Types.ObjectId,
      userId: String,
      email: String,
      name: String,
      district: String,
      branch: String,
    },

    // ── Branch ───────────────────────────────────────────────────────────────
    branch: {
      id: { type: mongoose.Schema.Types.ObjectId, ref: "Branch", default: null },
      name: { type: String, default: "" },
    },

    // ── Workflow / status ────────────────────────────────────────────────────
    status: { type: String, default: "pending" },
    workflowStage: { type: String, default: "contact creation" },
    history: [
      {
        updatedBy: String,
        updatedAt: Date,
        changes: String,
        stage: String,
      },
    ],

    // ── Audit ────────────────────────────────────────────────────────────────
    source: { type: String, default: "mobile" }, // where the submission originated
    submittedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    submittedAt: { type: Date, default: Date.now },

    // ── System rejection (e.g. auto-reject on low CIBIL) ─────────────────────
    rejection: {
      rejectedBy: { type: String, default: "" }, // e.g. "System"
      reason: { type: String, default: "" },
      rejectedAt: { type: Date, default: null },
    },

    // ── CIBIL summary (Xaler TransUnion) — Phase 4 ───────────────────────────
    // ONLY the summary needed by the application lives here. The complete
    // request/response (and the vendor report/PDF URL) are stored in the
    // separate CibilReport collection — never on the Application document.
    cibil: {
      score: { type: Number, default: null },
      status: { type: String, default: "" },   // vendor-reported status
      // Integration state, independent of the vendor status:
      //   "pending"       — accepted, awaiting downstream CIBIL processing
      //   "auto_rejected" — completed + auto-rejected on low score
      //   "unavailable"   — Xaler unreachable / invalid response
      state: { type: String, default: "" },
      // Decision outcome: "NTC" | "PASS" | "REJECT" (set by cibilProcessingService).
      result: { type: String, default: "" },
      reportDate: { type: String, default: "" },
      requestId: { type: String, default: "" },
      fetchedAt: { type: Date, default: null },
    },
  },
  { timestamps: true }
);

applicationSchema.index({ formId: 1 }, { unique: false, sparse: true });
applicationSchema.index({ status: 1 });
applicationSchema.index({ workflowStage: 1 });
applicationSchema.index({ status: 1, workflowStage: 1 });
// Phase 8: Pending CIBIL / pending lists filter by workflowStage and sort by
// createdAt — a compound index serves both in one pass.
applicationSchema.index({ workflowStage: 1, createdAt: -1 });
applicationSchema.index({ createdAt: -1 });
applicationSchema.index({ "dealerDetails.branch": 1 });
applicationSchema.index({ "dealerDetails.district": 1 });
applicationSchema.index({ dealer: 1 });

export default mongoose.model("Application", applicationSchema, "applications");
